-- schéma pokequiz

BEGIN;

DROP TABLE IF EXISTS 
"answer",
"quiz",
"question";

-- Table "answer"
CREATE TABLE IF NOT EXISTS "answer" (

  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "description" TEXT NOT NULL,
  "question_id" INTEGER NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz

);

-- Table "quiz"

CREATE TABLE IF NOT EXISTS "quiz" (

  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" TEXT NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz

);

-- Table "question"

CREATE TABLE IF NOT EXISTS "question" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "question" TEXT NOT NULL,
  -- 'Good answer',
  "answer_id" INTEGER NOT NULL REFERENCES "answer" ("id"),
  "quiz_id" INTEGER NOT NULL REFERENCES "quiz" ("id"),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);

ALTER TABLE "answer"
ADD FOREIGN KEY ("question_id") REFERENCES "question" ("id");

COMMIT; 



